### ISSUE TITLE
Default configuration of line lengths for git commit messages

### ISSUE THREAD

**Issue by dwsilk** [linz/template-python-hello-world#12]
Early discussion here: https://github.com/linz/template-python-hello-world/pull/9

By default, `gitlint` requires commit titles to be <72 chars and the commit body to be wrapped at 80 chars.

In terms of other services that we use:

GitHub will truncate titles with a  "show more" ellipses at 72 chars.

`dependabot` does restrict commit titles to <72 chars ([see here](https://github.com/dependabot/feedback/issues/165)) but doesn't restrict the commit body so its PRs will fail with a commit body length restriction, as it has [here](https://github.com/linz/template-python-hello-world/pull/11).

I propose:
- titles with a warning at 50 chars, hard limit at 72 chars
- body with a warning at 80 chars, no hard limit

This matches the default configuration of `commitlint`: https://github.com/conventional-changelog/commitlint/blob/master/docs/reference-rules.md

**Comment by blacha** [comment]
I am unsure if we need a warning on the body, the commitlint default rules have `body-max-line-length: Infinity` 

I was under the impression that editors will automatically wrap the body lines if too long.

**Comment by blacha** [comment]
Made a long line test commit here

https://github.com/linz/template-python-hello-world/commit/bd4d074635e16a65c61ac7f087b9333cf11056b3
