### ISSUE TITLE
Add docs about installing isort in git hooks

### ISSUE THREAD

**Issue by palmerj** [linz/template-python-hello-world#39]
I'm finding that sometimes VS Code isort "on save" stuff is not working that well for isort. It might be best to add some notes about installing isort as a git pre-commit hook in `.git/hooks/pre-commit`:

```python
#!/usr/bin/env python
import sys
from isort.hooks import git_hook

sys.exit(git_hook(strict=True, modify=False))
```

**Comment by danielAtLINZ** [comment]
Hi @palmerj , sure it was me you wanted to this one to?

**Comment by palmerj** [comment]
Sorry about that!

**Comment by dwsilk** [comment]
The "not working that well" stuff is documented here: https://github.com/linz/template-python-hello-world#vscode-configuration-2 (still waiting on `isort 5.0.0` to fix this)

..but yep a pre-commit hook could be recommended in addition to that.

**Comment by palmerj** [comment]
Up to you if you want to add. I need it cause VS code is not working and sometimes I use VIM too.

**Comment by dwsilk** [comment]
Note that `isort 5+` has landed with a black-compatible profile... but `pylint` requires `isort <5`, so can't upgrade without breaking `pylint`.

**Comment by l0b0** [comment]
We're now using isort 5.8.0, and isort works out of the box with `pre-commit`. should this ticket be closed?
